### ISSUE TITLE
เนื้อเรื่อง

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#10]

**Comment by r1chwo0n** [comment]
อันเนื้อเรื่องเข้าด่านอ่างแก้ว แล้วทำไมต้องอ่างแก้วอ่ะ

**Comment by r1chwo0n** [comment]
หมานถึงว่าเราจะไปเก็บอะไรที่ด่านอ่างแก้วอ่ะ คือพายุเข้าบลาๆ ของไปลอยอยู่ในน้ำ? ประมาณนี้ป่ะ

**Comment by r1chwo0n** [comment]
มาแล้วจ้า

**Comment by r1chwo0n** [comment]
ด่านแรก>หน้ามอ 
mission>เก็บตราช้างที่อกเสื้ออ่ะ เพราะจะทำเหมือนให้มันเป็นsymbolของนักศึกษาไปเลย ฟีลๆแบบเอ้อเป็นนักศึกษาทีนี่นะต้องมีอันนี้ไว้ครอบครองนะ สอดคล้องกับการที่เป็นด่านประตูมอพอดีแบบเปิดเข้าไปสู้ข้างในเป็นขั้นตอน Preparing

**Comment by r1chwo0n** [comment]
ด่านที่ 2>อ่างแก้ว
mission>ให้ไปไอเท็มเป็นเกียร์ของวิศวะ ตามเรื่องเล่า ตำนานความเชื่อที่เค้าว่ากันมา

**Comment by r1chwo0n** [comment]
ด่านที่3>อมช
mission>ข้าวหมูกรอบ! ชื่อดังมากในศูนย์อาหาร คนต่อแถวรอซื้อเยอะมาก นี่ก็เคยไปกินแต่แอบหวานไปหน่อย555555

**Comment by r1chwo0n** [comment]
![IMG_4773](https://user-images.githubusercontent.com/110924108/189940756-8dc38e68-0e28-45e7-b72d-9cbea0b8e58f.png)

**Comment by r1chwo0n** [comment]
สวัสดีค่ะ! A day in MorChor ยินดีต้อนรับค่ะ😄 วันนี้เราจะพาท่านไปเปิดประสบการณ์ในรั้วมหาวิทยาลัยเชียงใหม่กันค่ะ ก่อนอื่นเลยเราจะต้องมีสัญลักษณ์ติดตัวเพื่อบ่งบอกว่าเป็นชาวมชก่อนนะคะ อย่างรู้ล่ะสิคะว่าเป็นอะไร

>ขึ้นรูปไอเทม< 
Ta da~~~ เข็มกลัดรูปช้างถือคบเพลิงนั้นเองค่ะ สิ่งนี่คือตราของมหาวิทยาลัยเลยนะคะ! เราจึงอยากให้ท่านทำ mission ของเราก่อนะคะ เพื่อเป็นการเตรียมตัวเข้าสู่รั้วมหาวิทยาลัยค่ะ

Mission : เก็บช้างถือคบเพลิงให้ครบ
Enjoy your mission! Fighting!

**Comment by r1chwo0n** [comment]
ได้ปะเนี่ย555555

**Comment by r1chwo0n** [comment]
สถานที่ถัดไปที่เราจะแนะนำท่านให้รู้จักคือ อ่างแก้ว มช นั่นเองงง เชื่อว่าท่านต้องเคยได้ยินชื่อเสียงของที่นี่มาก่อนอย่างแน่นอน อ่างแก้วถือเป็นสถานที่พักใจของเหล่าคนเหงาได้ดีเลยทีเดียว ไม่ว่าจะพักใจจากเรื่องเรียนหรือเรื่องรัก 

สำหรับปัญหาชีวิตของเด็กมหาลัยก็คงหนีไม่พ้น ‘ปัญหาหัวใจ’ ที่นี่ก็มีเรื่องเล่าเช่นกันค่ะ เค้าว่ากันว่าใต้อ่างแก้วนั้นมีเกียร์ของชาววิศวะจมอยู่เยอะมาก แต่เอ้ะ แล้วทำไมถึงเป็นแบบนั้นได้นะ ถ้าอยากพิสูจน์ว่าเรื่องนี้เป็นจริงหรือไม่ ขอให้ท่านสนุกกับ mission ของเราค่ะ😄

Mission : เก็บเกียร์ให้ครบ
Good luck!

**Comment by r1chwo0n** [comment]
เสริมเติมแต่งหรือเปลี่ยนได้เน้อ คิดมุกมิออก55555

**Comment by r1chwo0n** [comment]
ตอนนี้ท่านคงเหนื่อยแล้วสินะคะ มาเติมพลังงานกันหน่อยดีกว่าค่ะ ที่มชเรามีศูนย์อาหารแห่งใหม่ใจกลางมหาวิทยาลัยที่ได้รวมร้านเด็ดร้านดังเอาไว้ให้ท่านแล้ว (กระซิบ) เราอยากแนะนำให้ท่านรู้จักกับ ‘ข้าวหมูกรอบ’ ร้านข้าวหมูกรอบที่นี่คนต่อแถวเยอะมากกกกก แม้ว่าบางคนจะหิวมากแต่ก็ยังยอมรอต่อแถวซื้อกันเลยทีเดียวค่ะ เรียกได้ว่าคงเป็นร้านที่ขายดีที่สุดในศูนย์อาหารของเราแล้วแหละค่ะ555555 แต่ๆๆๆ ที่มาแนะนำท่านได้นี้ไม่ได้มาจากสถิติการต่อแถวแต่อย่างใด เราได้ไปลองมาแล้วค่ะ😏 อร่อยมาก! แสงออกปากกันไปเลยทีเดียว คุ้มค่าต่อการรอคอยเลยแหละค่ะ! เราจึงอยากให้ท่านได้ลิ้มลองรสชาติของหมูกรอบๆ กับข้าวร้อน แล้วก็น้ำจิ้มแจ่วที่จัดจ้านไปพร้อมกับเราผ่านด่านนี้กันค่ะ

Mission : เก็บข้าวหมูกรอบให้หมด
Enjoy your meal😘 ทานให้อร่อยนะคะ

**Comment by r1chwo0n** [comment]
(ถ้ามีด่านโบนัส)
ใครอยากเป็นเสดถี ชั้นน่ะสิ ชั้นน่ะสิ  มาผ่อนคลายกันดีกว่าค่ะทุกโค้นนน เราขอต้อนรับท่านเข้าสู้ด่านโบนัส🎉🎉🎉 ด่านนี้เป็น top secret เลยนะคะ🤫 ช่วงนี้ เศรษฐกิจไม่ค่อยดีล่ะสิคะ มา ‘วิ่งkeptเหรียญ’ กันดีกว่าค่ะ โกยได้โกยเลยนะคะด่านนี้ ขอให้ท่าน enjoy ค่ะ และทางเราได้ขอลาไปก่อนนะคะ ขอบคุณท่านที่มาเข้าร่วม A day in MorChor กับเรา แล้วพบกันใหม่ ขอบคุณค่ะ! 
Good luck!

**Comment by r1chwo0n** [comment]
(ถ้ามีด่านโบนัส)
ใครอยากเป็นเสดถี ชั้นน่ะสิ ชั้นน่ะสิ  มาผ่อนคลายกันดีกว่าค่ะทุกโค้นนน เราขอต้อนรับท่านเข้าสู้ด่านโบนัส🎉🎉🎉 ด่านนี้เป็น top secret เลยนะคะ🤫 ช่วงนี้ เศรษฐกิจไม่ค่อยดีล่ะสิคะ มา ‘วิ่งkeptเหรียญ’ ในสนามกีฬากลางของเรากันดีกว่าค่ะ ได้ทั้งคลายเครียดและช่วยเรื่องสุขภาพ😉 โกยได้โกยเลยนะคะด่านนี้ ขอให้ท่าน enjoy ค่ะ และทางเราได้ขอลาไปก่อนนะคะ ขอบคุณท่านที่มาเข้าร่วม A day in MorChor กับเรา แล้วพบกันใหม่ ขอบคุณค่ะ! 
Good luck!

**Comment by r1chwo0n** [comment]
(แบบไม่มีด่านโบนัส)
งานเลี้ยงย่อมมีวันเลิกลา และแล้วเราก็ดำเนินกันมาสุดทางแล้ว เราขอขอบคุณท่านที่อยู่กับเรามาจนถึงตอนนี้ A day in MorChor ก็ได้มาถึงตอนจบ แล้วพบกันใหม่ค่ะ! ขอบคุณที่มาร่วมสนุกกับเรานะคะ
Thx u💖

**Comment by r1chwo0n** [comment]
บทแบบนี้ได้ป่ะ😅

**Comment by r1chwo0n** [comment]
อยากให้ปรับตรงไหน เปลี่ยนอะไรยังไง พิมมาเลยเน้อ
