### ISSUE TITLE
ระบบเดิน

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#11]
-ระบบเดิน
ขอแบบ8ทิศ
ใช้เป็นwasd

**Comment by NMBxNIGHT** [comment]
![ระบบเดิน](https://user-images.githubusercontent.com/110953295/189393845-51d84d4d-4844-4867-a35f-bd30d8dc961a.jpg)

sprite เดินได้แล้วทั้ง8ทิศเลย กำหนดความไวในการเดินได้

**Comment by NMBxNIGHT** [comment]
![ระบบเดิน](https://user-images.githubusercontent.com/110953295/189395041-ff689730-0072-4072-b13e-2e9c66c109db.jpg)
ทำเสร็จแล้วเด้อออ เดิน/หันได้8ทิศ กำหนดความเร็วได้

**Comment by BUFFVODAKA** [comment]
อันบนม่วงๆคืออะไรอะ

**Comment by NMBxNIGHT** [comment]
สีม่วงไม่เกี่ยว555
อันนั้นลองเทสแถบเลือดดูอะ
