### ISSUE TITLE
หน้าต่าง ui

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#13]
-ปกเกม(หน้าเมนู)
-หน้าวิธีเล่น
-หน้าgame over

**Comment by r1chwo0n** [comment]
![IMG_4588](https://user-images.githubusercontent.com/110924108/189380498-3fc177e9-1d8e-4ae4-ab81-5fc355617ecf.JPG)

**Comment by r1chwo0n** [comment]
[https://imgur.com/a/t1Zu8Gb.jpg](url)

**Comment by r1chwo0n** [comment]
[https://drive.google.com/file/d/1lii5xURax9V91L2Xp-i7hu6iRBJIJXkk/view?usp=sharing](url)

**Comment by r1chwo0n** [comment]
![IMG_4588](https://user-images.githubusercontent.com/110924108/189382831-13b65cf2-9432-4a9b-8ed9-9e5b5dd87fab.JPG)

**Comment by BUFFVODAKA** [comment]
![2Q](https://user-images.githubusercontent.com/110962980/189382146-a3539bf0-7fcf-4338-817e-494f103eff61.png)

**Comment by BUFFVODAKA** [comment]
ได้ๆแต่ลงสีพน.ทันมะ

**Comment by r1chwo0n** [comment]
คิดว่าทัน แต่เกมเราชื่ออะไรอ่ะ

**Comment by BUFFVODAKA** [comment]
keptแหละ

**Comment by r1chwo0n** [comment]
ไม่เปลี่ยนจริงอ่ะ55555

**Comment by r1chwo0n** [comment]
![IMG_4612](https://user-images.githubusercontent.com/110924108/189468145-40cec345-067d-42e0-9c6e-1f57b14714f7.PNG)
![IMG_4611](https://user-images.githubusercontent.com/110924108/189468154-75a16907-202b-47ca-9b44-dc4d65e14126.JPG)

**Comment by r1chwo0n** [comment]
อันนี้ปกเกม ได้ป่ะ

**Comment by BUFFVODAKA** [comment]
ได้ๆแต่ขอให้มีinstruction(ปุ่มคำแนะนำ)เพิ่มด้วย

**Comment by r1chwo0n** [comment]
คำแนะนำเอาไว้ใช้ทำอะไรอ่ะ

**Comment by r1chwo0n** [comment]
เขียนวิธีเล่นเกมมาให้หน่อยได้มั้ย ว่าต้องแนะนำยังไง กับหน้าเกมoverมีอะไรบ้าง

**Comment by r1chwo0n** [comment]
ปุ่มคำแนะนำเอาไว้ทางซ้ายมือเนาะ มันว่างอยู่

**Comment by r1chwo0n** [comment]
![IMG_4617](https://user-images.githubusercontent.com/110924108/189490128-23e2e0dc-1c84-438a-a74b-2c672d281fe3.PNG)
![IMG_4619](https://user-images.githubusercontent.com/110924108/189490323-e0796e46-fef9-4563-a294-1bf5185212a6.JPG)

**Comment by r1chwo0n** [comment]
อันนี้รึป่าว เอาไว้แนะนำวิธีการเล่นคือก่อนเริ่มเล่นเกมก็ให้กดตรงนี้ก่อน

**Comment by BUFFVODAKA** [comment]
ลองเอาเป็นแบบHOW TO PLAYมะ

**Comment by r1chwo0n** [comment]
เป็นปุ่มใช่ป่ะ สี่เหลี่ยมแล้วมีคำว่าHow to playข้างใน

**Comment by BUFFVODAKA** [comment]
> เขียนวิธีเล่นเกมมาให้หน่อยได้มั้ย ว่าต้องแนะนำยังไง กับหน้าเกมoverมีอะไรบ้าง
มี-wasdเดิน 
  -Fเก็บของ
  -shiftวิ่ง

**Comment by BUFFVODAKA** [comment]
แล้วก้บอกกติกาเกมไปว่าเดินชนแล้วเสียเลือด
เลือดหมดแล้วgame over

**Comment by r1chwo0n** [comment]
อันฉากกับตัวปุ่มอะไรพวกนี้พอเอาไปวางแล้วมันทับกันจนเทสโค้ดลำบากมั้ย ดูให้หน่อย เดี๋ยวไปทำให้มันเต็มๆ

**Comment by r1chwo0n** [comment]
> เป็นปุ่มใช่ป่ะ สี่เหลี่ยมแล้วมีคำว่าHow to playข้างใน

ตอบอันนี้โหน่ยยย

**Comment by BUFFVODAKA** [comment]
> > เป็นปุ่มใช่ป่ะ สี่เหลี่ยมแล้วมีคำว่าHow to playข้างใน
> 
> ตอบอันนี้โหน่ยยย

yes

**Comment by r1chwo0n** [comment]
Okayyy

**Comment by r1chwo0n** [comment]
![IMG_4620](https://user-images.githubusercontent.com/110924108/189491269-898e5cc3-a7cd-4e4f-b2d4-9064fcf9cfcd.JPG)
![IMG_4621](https://user-images.githubusercontent.com/110924108/189491276-e6504973-07fe-4c29-921f-7f4ba6ce4bd7.PNG)

**Comment by r1chwo0n** [comment]
แบบนี้ได้ป่ะ

**Comment by BUFFVODAKA** [comment]
มันเกยถนนอะลองเอาจอยออกดู

**Comment by r1chwo0n** [comment]
อ๋อออแปปๆ

**Comment by r1chwo0n** [comment]
![IMG_4622](https://user-images.githubusercontent.com/110924108/189491571-080494b3-8990-4dc4-8b34-6068e2374e9a.JPG)
![IMG_4623](https://user-images.githubusercontent.com/110924108/189491583-39325f55-72c2-4849-b3e6-a05d755df21a.PNG)
แบบนี้ป่ะ

**Comment by r1chwo0n** [comment]
เสียเลือดนี่เสียหัวใจใช่ป่ะ หัวใจเป็นดวงๆหรือว่าเป็นแบบไหนอ่ะ

**Comment by BUFFVODAKA** [comment]
หัวใจ

**Comment by r1chwo0n** [comment]
3ดวง?

**Comment by r1chwo0n** [comment]
![IMG_4626](https://user-images.githubusercontent.com/110924108/189494777-5d2d9e35-092a-468e-af18-2edab74b94a4.PNG)

**Comment by r1chwo0n** [comment]
![IMG_4627](https://user-images.githubusercontent.com/110924108/189494905-7fe9f094-3235-41a5-a8f9-4ecbb0be52cf.JPG)
![IMG_4628](https://user-images.githubusercontent.com/110924108/189494913-1e447883-76ae-4467-b66d-0d74f9d104e6.PNG)
![IMG_4629](https://user-images.githubusercontent.com/110924108/189494914-4f5934fc-0736-4dc5-bddc-94d777eacf48.PNG)

ได้ป่ะ

**Comment by r1chwo0n** [comment]
![IMG_4632](https://user-images.githubusercontent.com/110924108/189496370-41e1d2ae-b2a3-4a51-a28f-2f0d480c4068.PNG)
![IMG_4634](https://user-images.githubusercontent.com/110924108/189496373-22aa09ce-373c-43aa-9967-87c76d9c100c.PNG)
![IMG_4635](https://user-images.githubusercontent.com/110924108/189496377-9cd0ef2c-b552-43a4-b38f-40bd1d2e1ac5.PNG)

**Comment by r1chwo0n** [comment]
ต้องมีหน้าrankingด้วยมั้ย

**Comment by BUFFVODAKA** [comment]
ยัง

**Comment by r1chwo0n** [comment]
kkkkk

**Comment by r1chwo0n** [comment]
![IMG_4656](https://user-images.githubusercontent.com/110924108/189518294-9ac7db54-f9d9-4a59-9993-f936167a8186.PNG)

**Comment by r1chwo0n** [comment]
![IMG_4664](https://user-images.githubusercontent.com/110924108/189520294-6b8c1db0-7af1-44bb-b2ca-9e2b0ac84bbc.jpeg)

**Comment by r1chwo0n** [comment]
![IMG_4665](https://user-images.githubusercontent.com/110924108/189520330-7b1269a0-be1d-437d-af78-aa1ad4a34370.png)

**Comment by r1chwo0n** [comment]
![IMG_4669](https://user-images.githubusercontent.com/110924108/189521388-409bf
![IMG_4670](https://user-images.githubusercontent.com/110924108/189521398-9b9858ae-5
![IMG_4671](https://user-images.githubusercontent.com/110924108/189521401-ba128951-7d2f-4658-b265-4e4add873d07.png)
bdc-41a2-a8ce-facefd3ef5d5.png)
b4b-b649-4d91-8f4d-f93c5317faab.png)

**Comment by r1chwo0n** [comment]
![IMG_4669](https://user-images.githubusercontent.com/110924108/189521425-f949f6ec-63a2-4e34-b0eb-b022ac702c18.png)

**Comment by r1chwo0n** [comment]
![IMG_4670](https://user-images.githubusercontent.com/110924108/189521436-61bceda1-3cf8-4e42-96f2-e935114f2396.png)

**Comment by r1chwo0n** [comment]
![IMG_4671](https://user-images.githubusercontent.com/110924108/189521452-838a6a02-b779-41f5-adbb-c32aa43c13ff.png)

**Comment by r1chwo0n** [comment]
![IMG_4833](https://user-images.githubusercontent.com/110924108/190215591-24560fec-449c-4274-852f-f66a8a2342ba.jpeg)

**Comment by r1chwo0n** [comment]
![IMG_4831](https://user-images.githubusercontent.com/110924108/190215661-d28279e2-96d3-434b-9402-5cd6ad068f68.png)

![IMG_4832](https://user-images.githubusercontent.com/110924108/190215716-729b001a-3777-4177-ad46-ef13f2c756d2.png)

**Comment by r1chwo0n** [comment]
![IMG_4835](https://user-images.githubusercontent.com/110924108/190216373-63e4bad8-2f85-46a8-9f79-d79c12764104.jpeg)
อันนี้แบบสามด่านจบ ไม่มีด่านโบนัส
