### ISSUE TITLE
สิ่งกีดขวาง

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#14]

**Comment by NMBxNIGHT** [comment]
![image](https://user-images.githubusercontent.com/110953295/189521827-441e1e75-13b3-4a03-a3f7-50f628600ec6.png)
ตอนนี้ทำไว้ประมาณนี้ คือให้ สิ่งกีดขวางเคลื่อนที่ตลอดเวลา มีตรวจว่าชนตัวละครไหม

**Comment by NMBxNIGHT** [comment]
มีอะไรอยากให้เพิ่มเติมก็บอกได้เน้อ

**Comment by NMBxNIGHT** [comment]
Update เกี่ยวกับตัวสิ่งกีดขวาง(รถ)

- [ รถสามารถไปวิ่งที่เลนอื่นได้แล้ว]
- [สามารถวิ่งไป-กลับได้(จากอีกเลนนึง)]

![image](https://user-images.githubusercontent.com/110953295/189663128-68c1044d-0339-4075-b689-1227ea07bcdb.png)
