### ISSUE TITLE
sound effect

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#15]
ขอเป็นไฟล์mp3นะแล้วก้รวมเป็นfolder google driveอันเดียวเลย
"เสียง"
-กด
-เดิน
-ตาย
-เก็บของ

**Comment by Exzqqq** [comment]
https://user-images.githubusercontent.com/110964410/189321102-702e7c38-ad66-434b-a67e-3eda8fd985b8.mp4


https://user-images.githubusercontent.com/110964410/189321108-37af21c7-56b0-439a-9b4d-5288d6304a46.mp4

**Comment by Exzqqq** [comment]
เพลง BG

https://drive.google.com/file/d/1EkTstRrJSN5Mypb73Qcev2izYr3PQ4yx/view

**Comment by Exzqqq** [comment]
เสียงclick mouse

https://user-images.githubusercontent.com/110964410/189333542-c90615c4-9c18-497b-85df-a64d7dca785d.mp4

**Comment by BUFFVODAKA** [comment]
ขอเป็นไฟล์mp3นะแล้วก้รวมเป็นfolder google driveอันเดียวเลย

**Comment by Exzqqq** [comment]
ไฟล์เสียงทั้งหมดเลยนะเป็นmp3 
ตอนนนี้เหลือแค่เสียงตอนตาย

https://drive.google.com/drive/folders/1z148HILQOhF-n9XquLWccB4LEkNUajuk?usp=sharing

**Comment by BUFFVODAKA** [comment]
เปิดสิทธิ์เข้าถึงด้วย

**Comment by Exzqqq** [comment]
เพิ่มเสียงตอนตายกับเพลงหน้าหลักให้แล้วนะ
