### ISSUE TITLE
ออกแบบตัวด่าน

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#17]
หน้ามอ

**Comment by Exzqqq** [comment]
ร่างด่านอ่างแก้ว

![IMG_4933](https://user-images.githubusercontent.com/110964410/189412145-4c7a78ab-a940-4407-9868-5492fcb81bf2.PNG)
![IMG_4932](https://user-images.githubusercontent.com/110964410/189412122-b7c69bbf-015a-4377-895a-bbc0ee1ca5a4.PNG)

**Comment by Exzqqq** [comment]
![IMG_4933](https://user-images.githubusercontent.com/110964410/189412449-5da41d55-6855-46d2-b45f-c11a867e2cac.PNG)

**Comment by r1chwo0n** [comment]
เราจะไม่โดนเรื่องขอนไม้ในอ่างแก้วเหมือนใบบัวของกลุ่มเพื่อนใช่มั้ย🥶

**Comment by BUFFVODAKA** [comment]
ก้สร้างเนื่อเรื่องว่าเมื่อวานพายุเข้า

**Comment by r1chwo0n** [comment]
คือก่อนเข้าด่านมีคัทซีนหรอ

**Comment by Exzqqq** [comment]
ด่านหน้ามอ


![IMG_4936](https://user-images.githubusercontent.com/110964410/189519613-473d1c01-5e15-477b-8179-58e848afadc2.PNG)

![IMG_4935](https://user-images.githubusercontent.com/110964410/189519608-4871fbde-daac-4ace-a0b8-01748e0f078e.PNG)

**Comment by Exzqqq** [comment]
แก้ด่าน 
![IMG_4937](https://user-images.githubusercontent.com/110964410/189522073-546d6280-8cda-40e0-ad44-6127917fc3b5.PNG)
![IMG_4938](https://user-images.githubusercontent.com/110964410/189522079-8bc240df-d0e2-49e8-89c9-43b90a1872ac.PNG)

**Comment by Exzqqq** [comment]
ด่าน3อมชนะ เราไม่คิดค่อยออกอะ มีไอเดียอะไรcommentได้นะ

![IMG_4939](https://user-images.githubusercontent.com/110964410/189537874-b9410c0d-a5a2-477c-8a5c-e3c65da46fed.PNG)
![IMG_4940](https://user-images.githubusercontent.com/110964410/189537884-153548b0-9882-4001-a204-8710ea9dfc38.PNG)

**Comment by r1chwo0n** [comment]
![IMG_4717](https://user-images.githubusercontent.com/110924108/189613961-a5fdc023-3821-4564-9402-b6d012fd3879.jpeg)
ได้ป่ะ

**Comment by BUFFVODAKA** [comment]
ได้
