### ISSUE TITLE
ระบบเลือด

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#18]

**Comment by NMBxNIGHT** [comment]
![เลือด1](https://user-images.githubusercontent.com/110953295/189396100-c6032179-7f5c-4364-a86d-f22b0a7f5edc.jpg)
![เลือด2](https://user-images.githubusercontent.com/110953295/189396111-0cfed5e2-8f15-4f54-8262-bd15c9e89e79.jpg)
อันนี้ลองทำไว้คร่าวๆคือ มีหลอดเลือดแล้วถ้าเลือดลดถึงจุดๆนึงหลอดเลือดก็จะลดลง ถ้าเหลือหมดก็ Game overเนาะ
