### ISSUE TITLE
สิ่งกีดขวาง

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#19]
เป็นแบบมุมมองจากด้านบน
-รถ3-4แบบ
-มอไซ2-3แบบ
-ท่อนซุง
-หมา
-คนติดcovid

**Comment by r1chwo0n** [comment]
![IMG_4595](https://user-images.githubusercontent.com/110924108/189394606-7adf9726-c948-4a28-bd6a-eecd5a7779ce.PNG)

**Comment by r1chwo0n** [comment]
![IMG_4598](https://user-images.githubusercontent.com/110924108/189400003-ebb6453a-dc36-42b4-9b61-0ddfb86b8ff9.PNG)

**Comment by r1chwo0n** [comment]
![IMG_4653](https://user-images.githubusercontent.com/110924108/189517653-43b4b090-1d0b-4861-b624-03b4e8a8c799.PNG)
![IMG_4651](https://user-images.githubusercontent.com/110924108/189517660-dd54612a-4a21-4f52-b15c-0a2d1249c436.PNG)
![IMG_4649](https://user-images.githubusercontent.com/110924108/189517661-547ac244-cc31-43b1-83be-d8dfe03d9dbd.PNG)

**Comment by r1chwo0n** [comment]
![IMG_4697](https://user-images.githubusercontent.com/110924108/189536525-21bbfa5d-f083-40ad-ad22-0983c0403dab.png)
![IMG_4698](https://user-images.githubusercontent.com/110924108/189536539-623d866b-66e1-4aa6-bc9a-6e77f3dcb0e8.png)

**Comment by r1chwo0n** [comment]
![IMG_4699](https://user-images.githubusercontent.com/110924108/189536547-cb5435b4-e694-46de-844e-070cfc09f975.png)
![IMG_4700](https://user-images.githubusercontent.com/110924108/189536562-a18d1a92-9242-458e-97dc-b1fb7b30fee2.png)
![IMG_4701](https://user-images.githubusercontent.com/110924108/189536574-4ee28b4f-6542-434f-9366-d4ae0586460d.png)

**Comment by r1chwo0n** [comment]
![IMG_4696](https://user-images.githubusercontent.com/110924108/189602359-8203d67f-cb9c-4a1e-894b-32e9b51e3f78.png)

**Comment by r1chwo0n** [comment]
![IMG_4738](https://user-images.githubusercontent.com/110924108/189684121-3e0b88b3-3e10-4cbf-bc07-51afd072c640.png)
![IMG_4739](https://user-images.githubusercontent.com/110924108/189684183-3ac40926-8a83-4b01-8012-e4b9022a840a.png)

**Comment by r1chwo0n** [comment]
![IMG_4742](https://user-images.githubusercontent.com/110924108/189688327-784afac4-deeb-4319-96e5-70121f7df195.png)

**Comment by r1chwo0n** [comment]
![IMG_4738](https://user-images.githubusercontent.com/110924108/189688402-e3ddc80d-75e4-4d34-9377-5cf1957184a3.png)

**Comment by r1chwo0n** [comment]
![IMG_4743](https://user-images.githubusercontent.com/110924108/189690839-4632bd02-fe6a-42f1-800e-e28d01a91911.png)

**Comment by r1chwo0n** [comment]
อันนี้เปลี่ยนสีกระจกรถนิดนึงนะ มันกลืนไปกับถนนอ่ะ🥹
![IMG_4674](https://user-images.githubusercontent.com/110924108/189691287-1a00b251-8f5d-4c28-94c7-41030c7fc7f1.png)

**Comment by r1chwo0n** [comment]
![IMG_4676](https://user-images.githubusercontent.com/110924108/189691339-70f248c1-363a-4be0-9387-3e668bfbe438.png)

**Comment by r1chwo0n** [comment]
![IMG_4744](https://user-images.githubusercontent.com/110924108/189694764-d6cfd08f-871d-4858-9da6-f9f588a21be4.png)

**Comment by r1chwo0n** [comment]
![IMG_4767](https://user-images.githubusercontent.com/110924108/189883218-a7332cdc-aeec-4cbe-86f8-dd11ebe54760.png)
![IMG_4768](https://user-images.githubusercontent.com/110924108/189883265-d708365d-909b-4f1f-8244-bab9248d9bcb.png)
![IMG_4769](https://user-images.githubusercontent.com/110924108/189883296-bf6a3f78-7625-49d3-9dd7-80ee60bf6f67.png)

**Comment by r1chwo0n** [comment]
![IMG_4792](https://user-images.githubusercontent.com/110924108/190057777-cd2896d1-8bc5-4e7c-a969-1300eeeee2a6.png)
![IMG_4793](https://user-images.githubusercontent.com/110924108/190057807-9d4beddd-b21f-471b-ba56-38f663ba525a.png)

**Comment by r1chwo0n** [comment]
![IMG_4794](https://user-images.githubusercontent.com/110924108/190057844-9b66e836-e238-4e13-a228-78076ff2b2a4.png)
![IMG_4795](https://user-images.githubusercontent.com/110924108/190057862-1117c8a4-0884-47e7-b27f-8135984f286e.png)
