### ISSUE TITLE
คำนวนคะแนน+เก็บของ

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#20]

**Comment by NMBxNIGHT** [comment]
![image](https://user-images.githubusercontent.com/110953295/189522379-003ef1b6-4b12-45dc-9e12-49f2dd43a813.png)
อันนี้เป็นไอเทมที่เอาไว้นับคะแนนนะก็คือ ถ้าตัวละครเดินไปชนไอเทมก็จะหายไปแล้วได้คะแนนเพิ่มเนาะ แล้วถ้ามีสิ่งกีดขวาง(รถ)วิ่งผ่านอะมันจะหายไปจากฉากแว้บนึงเหมือนโดนรถบัง

เพิ่มเติมได้เด้อ

**Comment by NMBxNIGHT** [comment]
ไอเทมที่ให้เก็บเพื่อผ่านด่านเสร็จแล้วเด้อ จะให้แก้ตรงไหนบอกได้เลย
