### ISSUE TITLE
demo game

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#23]

**Comment by NMBxNIGHT** [comment]
https://scratch.mit.edu/projects/729995843

ประมาณนี้โอเคได้มั้ยอะ ยังไม่ได้ใส่มอไซค์

**Comment by BUFFVODAKA** [comment]
ยังไม่มีanimationเดินอะ

**Comment by NMBxNIGHT** [comment]
ใช่ๆ กำลังคิดอยู่ว่าจะใส่ยังไงดี ตอนแรกลองแล้วมันไม่รอด 555

**Comment by BUFFVODAKA** [comment]
https://scratch.mit.edu/projects/730976245
รวมmenuละ

**Comment by NMBxNIGHT** [comment]
https://scratch.mit.edu/projects/731239838/editor/

- ใส่ระบบเลือด
- รถมอไซค์
- โคลนตัวรถยนค์ให้มีรถในถนนเพิ่มขึ้น

**Comment by BUFFVODAKA** [comment]
เปิดไม่ได้อะ

**Comment by NMBxNIGHT** [comment]
ลืมแชร์ๆ
ตอนนี้แชร์ละ ลองใหม่ๆ

**Comment by Exzqqq** [comment]
ทำไมอยู่ดีๆเดินหน้าพร้อมทิศทางมันวิ่งเร็วจัง passiveหรอ
ตอนgmae over ศพมันยังวิ่งได้

> https://scratch.mit.edu/projects/731239838/editor/
> 
> * ใส่ระบบเลือด
> * รถมอไซค์
> * โคลนตัวรถยนค์ให้มีรถในถนนเพิ่มขึ้น

**Comment by BUFFVODAKA** [comment]
https://scratch.mit.edu/projects/731738810
