### ISSUE TITLE
item

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#28]
แยกเป็นด่านๆนะ

**Comment by r1chwo0n** [comment]
ด่านแรก>หน้ามอ 
mission>เก็บตราช้างที่อกเสื้ออ่ะ เพราะจะทำเหมือนให้มันเป็นsymbolของนักศึกษาไปเลย ฟีลๆแบบเอ้อเป็นนักศึกษาทีนี่นะต้องมีอันนี้ไว้ครอบครองนะ สอดคล้องกับการที่เป็นด่านประตูมอพอดีแบบเปิดเข้าไปสู้ข้างในเป็นขั้นตอน Preparing

**Comment by r1chwo0n** [comment]
ด่านที่ 2>อ่างแก้ว
mission>ให้ไปไอเท็มเป็นเกียร์ของวิศวะ ตามเรื่องเล่า ตำนานความเชื่อที่เค้าว่ากันมา

**Comment by r1chwo0n** [comment]
ด่านที่3>อมช
mission>ข้าวหมูกรอบ! ชื่อดังมากในศูนย์อาหาร คนต่อแถวรอซื้อเยอะมาก นี่ก็เคยไปกินแต่แอบหวานไปหน่อย555555

**Comment by r1chwo0n** [comment]
![IMG_4758](https://user-images.githubusercontent.com/110924108/189875078-d193efea-8297-4614-b15d-79319d24351c.png)

**Comment by r1chwo0n** [comment]
![IMG_4766](https://user-images.githubusercontent.com/110924108/189878526-d814d5d0-b664-4fc0-9bf5-5a3f97267c41.png)

**Comment by r1chwo0n** [comment]
![IMG_4807](https://user-images.githubusercontent.com/110924108/190080574-97d153d9-d167-4592-9cba-e2536a30c998.png)
