### ISSUE TITLE
BUGเดินไว

### ISSUE THREAD

**Issue by Exzqqq** [BUFFVODAKA/Project7#30]
1.spirte หลังจากโดนชนครั้งที่1ก็วิ่งเร็วขึ้นแบบไม่ทราบสาเหตุ

2.spirteสามาเดินได้ตอนgame over

**Comment by NMBxNIGHT** [comment]
ที่แก้มาล่าสุดเหมือนไม่มีเดินไวแล้วนะ

ถ้ายังไงลองเทสดููอีกทีเนาะ
