### ISSUE TITLE
ตัวเกม

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#36]

**Comment by NMBxNIGHT** [comment]
Latest game ver.
https://scratch.mit.edu/projects/733809848

**Comment by BUFFVODAKA** [comment]
Lastest game ver.jingๆ
https://scratch.mit.edu/projects/734582083

**Comment by NMBxNIGHT** [comment]
- แก้ how 2 play เป็นล่าสุดแล้ว
- ใส่จุดเิกดไอเทมของด่านโบนัสแล้ว

https://scratch.mit.edu/projects/734722046/editor/
