### ISSUE TITLE
bug รถเกิดทับกัน

### ISSUE THREAD

**Issue by Exzqqq** [BUFFVODAKA/Project7#38]
มีบางครั้งที่รถเกิดทับกัน

<img width="257" alt="Screen Shot 2565-09-18 at 5 22 56 PM" src="https://user-images.githubusercontent.com/110964410/190925093-8a3a2516-5cb4-4c54-9b1f-cbdfe6139294.png">

**Comment by BUFFVODAKA** [comment]
แก้แล้วนะเป็นไง

**Comment by NMBxNIGHT** [comment]
แก้แล้วเด้อ คิดว่าไม่น่ามีปัญหาแล้วนะ
