### ISSUE TITLE
bugรถหาย

### ISSUE THREAD

**Issue by Exzqqq** [BUFFVODAKA/Project7#39]
มีบางครั้งที่itemในด่านกับรถหาย

<img width="890" alt="Screen Shot 2565-09-19 at 2 26 43 AM" src="https://user-images.githubusercontent.com/110964410/190925195-2542f50c-79e9-420a-9735-85f1dc437778.png">

คนมาเกิดรวมๆกันที่จุดเดียวกันแล้วเดินวนไปวนไป

<img width="164" alt="Screen Shot 2565-09-19 at 2 24 48 AM" src="https://user-images.githubusercontent.com/110964410/190925228-7ced680d-bc50-4461-af62-ffc02ed86fe3.png">

**Comment by NMBxNIGHT** [comment]
แก้ให้แล้วนะ
