### ISSUE TITLE
bugที่มีเหมือนกันทุกด่าน

### ISSUE THREAD

**Issue by Exzqqq** [BUFFVODAKA/Project7#40]
กดplay again แล้วicon homeยังอยู่หน้าจอไม่หายไป

<img width="409" alt="Screen Shot 2565-09-19 at 1 55 02 AM" src="https://user-images.githubusercontent.com/110964410/190925374-f9266c10-cbfb-464c-856d-895e578f970a.png">

**Comment by NMBxNIGHT** [comment]
แก้ให้แล้วลืมนิดหน่อย
