### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#42]
-concept
-game link

**Comment by NMBxNIGHT** [comment]
https://scratch.mit.edu/projects/734722046/

- ลิ้งเกมเด้ออ

**Comment by r1chwo0n** [comment]
[A day in MorChor.docx](https://github.com/BUFFVODAKA/Project7/files/9647893/A.day.in.MorChor.docx)
คอนเส้ปปป

**Comment by BUFFVODAKA** [comment]
home pageเส็จละนะต้องเพิ่มไรปะ

**Comment by r1chwo0n** [comment]
ครบล้ะะ

**Comment by BUFFVODAKA** [comment]
งั้นclose issueเลยนะ

**Comment by r1chwo0n** [comment]
โอเค
