### ISSUE TITLE
Members

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#44]
-รูปถ่ายตัวเอง
-บอกหน้าที่

**Comment by r1chwo0n** [comment]
![Members](https://user-images.githubusercontent.com/110924108/192317950-dbeaf277-c150-4d4b-a832-304b3ae2c81c.jpg)
แบบนี้ได้ป่ะ

**Comment by r1chwo0n** [comment]
![Members](https://user-images.githubusercontent.com/110924108/192320873-69671a1b-6a87-4815-bbb0-105da1e9b172.jpg)

**Comment by r1chwo0n** [comment]
อัพลงไดรฟ์แล้ว มีเปลี่ยนสีนิดหน่อยให้เข้ากับตัวเกม
