### ISSUE TITLE
spriteตัวละคร

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/Project7#9]
ท่าเดิน
ตาย
ว่ายน้ำ

**Comment by r1chwo0n** [comment]
ขอconsultมุมspriteหน่อยค้าบ

**Comment by r1chwo0n** [comment]
เห็นแต่หัวมุมtopเลยหรอ หรือว่ายังไง วาดคร่าวๆมาให้ดูหน่อยได้มั้ย

**Comment by r1chwo0n** [comment]
![IMG_4642](https://user-images.githubusercontent.com/110924108/189497581-ea2de08b-7b7e-4c89-a0e3-873b97f06a3b.PNG)
แบบนี้หรอ

**Comment by r1chwo0n** [comment]
ต้องการแบบไหน แนวไหน ตัวละครหันทิสไหนบ้าง พิมพ์ทิ้งไว้เลยเน้อ เดี๋ยวพนมาวาดต่อ

**Comment by BUFFVODAKA** [comment]
ขอสองรูปนะให้มันเปลี่ยนตอนเคลื่อนไหว

**Comment by r1chwo0n** [comment]
ก้าวซ้ายขวาปะ

**Comment by BUFFVODAKA** [comment]
ใช่

**Comment by r1chwo0n** [comment]
![IMG_4687](https://user-images.githubusercontent.com/110924108/189531990-4aa28650-3895-4965-a114-ed082428f701.png)
![IMG_4688](https://user-images.githubusercontent.com/110924108/189532008-16e8b880-8ac1-43a7-8f93-156d93578b4a.png)

**Comment by r1chwo0n** [comment]
![IMG_4689](https://user-images.githubusercontent.com/110924108/189532716-9991aaae-41e9-400a-855d-95536c6c7479.png)

![IMG_4690](https://user-images.githubusercontent.com/110924108/189532730-fb977d48-cc7a-4b66-943b-598e8575edfa.png)

**Comment by r1chwo0n** [comment]
![IMG_4695](https://user-images.githubusercontent.com/110924108/189534487-e675416e-4b09-4594-94b6-2977b8023a5f.png)

**Comment by r1chwo0n** [comment]
เสร็จล้ะ เรียบร้อย

**Comment by r1chwo0n** [comment]
แกเปากแปปป

**Comment by r1chwo0n** [comment]
เสร็จแน้ววว
